- name: enable the helper in configuration
  ini_file: dest="{{ tahoe_basedir }}/node/tahoe.cfg"
            section=helper
            option=enabled
            value=true
  notify: restart helper

- name: running handlers to read out a possibly updated helper furl
  meta: flush_handlers

- name: get the helper's furl
  register: helper_furl_cat
  action: command cat "{{ tahoe_basedir }}/node/private/helper.furl"
  retries: 20
  delay: 1
  until: helper_furl_cat|success
  changed_when: false

- name: setting hostvars['{{ ansible_nodename}}']['tahoe_helper_furl']
  set_fact: tahoe_helper_furl="{{ helper_furl_cat.stdout }}"

- name: print the helper furl
  debug: msg="Your helper furl is {{ helper_furl_cat.stdout }}"
