- name: enable the helper in configuration
  ini_file: dest="{{ tahoe_basedir }}/node/tahoe.cfg"
            section=helper
            option=enabled
            value=true
  register: helper_enabled_state

- name: run the freshly created helper the first time
  command: "tahoe start -C {{ tahoe_basedir }}/node"
  when: helper_enabled_state.changed

- name: stop the freshly created helper the first time
  command: "tahoe stop -C {{ tahoe_basedir }}/node"
  when: helper_enabled_state.changed

- name: get the helper furl
  command: cat "{{ tahoe_basedir }}/node/private/helper.furl"
  register: helper_furl_cat

- name: print the helper furl
  debug: msg="Your helper furl is {{ helper_furl_cat.stdout }}"
