- name: set default release priority {{ release }}
  blockinfile:
    dest: /etc/apt/preferences.d/000-release-pinning
    create: yes
    state: "{{ 'present' if present else 'absent' }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK for {{ suite }}"
    block: |
      Package: *
      Pin: release a={{ suite }}
      Pin-Priority: {{ pin_priority }}

- name: add repository to file in /etc/apt/sources.list.d
  lineinfile:
    path: "{{ file }}"
    regexp: '\s{{ suite }}\s'
    line: 'deb http://deb.debian.org/debian {{
             suite
           }} main contrib non-free'
    state: "{{ 'present' if present else 'absent' }}"
    create: yes

- name: remove repository from /etc/apt/sources.list
  lineinfile:
    path: "/etc/apt/sources.list"
    regexp: '\s{{ suite }}\s'
    state: absent
  when: not present

- name: add security repository to file in /etc/apt/sources.list.d
        (old format)
  lineinfile:
    path: "{{ file }}"
    regexp: 'security.*\s{{ suite }}[-/]updates\s'
    line: 'deb http://security.debian.org/debian-security {{
             suite
           }}/updates main contrib non-free'
    state: "{{ 'present'
                if present and release in security_old_format_releases
                else 'absent' }}"
    create: yes
  when: release not in no_security_repo_releases
        and '-' not in suite
        and '/' not in suite

- name: add security repository to file in /etc/apt/sources.list.d
        (new format)
  lineinfile:
    path: "{{ file }}"
    regexp: 'security.*\s{{ suite }}-security[-/]updates\s'
    line: 'deb http://security.debian.org/debian-security {{
             suite
           }}-security/updates main contrib non-free'
    state: "{{ 'present'
                if present and release not in security_old_format_releases
                else 'absent' }}"
    create: yes
  when: release not in no_security_repo_releases
        and '-' not in suite
        and '/' not in suite

- name: remove security repository from /etc/apt/sources.list
  lineinfile:
    path: "/etc/apt/sources.list"
    regexp: 'security.*\s{{ suite }}[-/]updates\s'
    state: absent
  when: not present
