- name: check if Apache2 is installed
  shell: type apache2
  changed_when: false
  ignore_errors: true
  register: apache2_installed_check

- name: add configuration files for Apache2
  file: src="/opt/admintools/etc/apache2/conf-available/{{ item }}"
        dest="/etc/apache2/conf-available/{{ item }}"
        state=link force=yes
  with_items:
    - basic-hardening.conf
    - httpoxy.conf
  when: apache2_installed_check|succeeded

- name: enable configurations for Apache2
  command: a2enconf "{{ item }}"
  with_items:
    - basic-hardening.conf
    - httpoxy.conf
  notify: restart apache2
  when: apache2_installed_check|succeeded
