# kernel support for Apparmor via role ``managed_node``

- name: query supported Linux security modules (to check for Apparmor)
  register: cat_lsm_result
  command: egrep '(^|,)apparmor(,|$)' /sys/kernel/security/lsm
  failed_when: false
  changed_when: false

- name: un/install packages for Apparmor
  package:
    name: "{{ item }}"
    state: "{{
      'present' if cat_lsm_result.rc == 0 else 'absent'
    }}"
  with_items:
    - apparmor
    - apparmor-profiles
