- name: install tools for managing apt-based systems
  package: name="{{ item.key }}" state="{{ item.value }}"
  with_dict: "{{ apt_tools |
                 combine(apt_tools_extra | default({})) }}"

- name: remove unneeded tools
  apt: name="{{ item }}" state=absent purge=yes
  with_items:
    - apt-xapian-index
    - netselect-apt

- name: cleanup files of unneeded packages
  file: path="{{ item }}" state=absent
  with_items:
    - /var/cache/apt-xapian-index

- name: make needrestart default to list services only
  lineinfile: dest=/etc/needrestart/conf.d/list-services-only.conf
              line="$nrconf{restart} = 'l';"
              state=present create=yes mode=0644

- name: make needrestart default to list required reboots only
  lineinfile: dest=/etc/needrestart/conf.d/list-required-reboots-only.conf
              regexp="\$nrconf\{kernelhints\}"
              line="$nrconf{kernelhints} = -1;"
              state=present create=yes mode=0644

- name: make needrestart default to use stdio "interface"
  lineinfile: dest=/etc/needrestart/conf.d/stdio-interface.conf
              regexp="\$nrconf\{ui\}"
              line="$nrconf{ui} = 'NeedRestart::UI::stdio';"
              state=present create=yes mode=0644

- name: remove needrestart's hook into apt to make sure it doesn't require
        user interaction (doing this via its settings seems to be unreliable)
  register: unhook_apt_result
  command: find /etc/apt -name "*needrestart*" -print -delete
  changed_when: unhook_apt_result.stdout != ""
  failed_when: unhook_apt_result|failed

- name: check needrestart version
  register: needrestart_version_lt_one
  shell: needrestart --version | grep "needrestart 0"
  changed_when: false
  failed_when: false

- name: restart services using outdated libraries (needrestart < 1.0)
  shell: needrestart -bra 2>/dev/null
  register: result
  changed_when: "result.stdout != ''"
  when: needrestart_version_lt_one.rc == 0

- name: restart services using outdated libraries (needrestart >= 1.0)
  shell: needrestart -blra 2>/dev/null
  register: result
  changed_when: "result.stdout != ''"
  when: needrestart_version_lt_one.rc == 1

- name: check for pending kernel updates
  command: needrestart -bk
  register: needrestart_result
  changed_when: False

- name: email root if machine needs a reboot
  # non-recent versions of needrestart read from stdin if newer kernels
  # are available, since we use '-b'
  shell: needrestart -bk | mail -s "$(hostname -f) needs a reboot" root
  # see https://github.com/ansible/ansible/issues/2769:
  when: "'NEEDRESTART-KSTA: 0' not in needrestart_result.stdout and
         'NEEDRESTART-KSTA: 1' not in needrestart_result.stdout"

- name: schedule yearly notification of unpurged APT packages
  cron: name="list (and thereby email) unpurged APT packages"
        job=/opt/admintools/dpkg_list-unpurged-packages.sh
        special_time=yearly

# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=812719
- name: get apticron version
  register: apticron_version_result
  shell: "dpkg -s apticron | grep 'Version: ' | awk '{print $2}'"
  changed_when: false

- name: patch apticron's bug "MIME-Version … No such file or directory"
  patch:
    dest: /usr/sbin/apticron
    src: /opt/admintools/apticron-1.1.59.patch
    remote_src: yes
    backup: yes
  when: apticron_version_result | version_compare('1.1.59', '==')
