- name: install desired tools
  package: name="{{ item }}" state=present
  with_items:
    - apticron
    - needrestart

- name: remove unneeded tools
  package: name="{{ item }}" state=absent
  with_items:
    - apt-xapian-index

- name: make needrestart default to list services only
  lineinfile: dest=/etc/needrestart/conf.d/list-services-only.conf
              line="$nrconf{restart} = 'l';"
              state=present create=yes mode=0644

- name: make needrestart default to list required reboots only
  lineinfile: dest=/etc/needrestart/conf.d/list-required-reboots-only.conf
              regexp="\$nrconf\{kernelhints\}"
              line="$nrconf{kernelhints} = -1;"
              state=present create=yes mode=0644

- name: make needrestart default to use stdio "interface"
  lineinfile: dest=/etc/needrestart/conf.d/stdio-interface.conf
              regexp="\$nrconf\{ui\}"
              line="$nrconf{ui} = 'NeedRestart::UI::stdio';"
              state=present create=yes mode=0644

- name: check needrestart version
  register: needrestart_version_lt_one
  shell: needrestart --version | grep "needrestart 0"
  changed_when: false
  failed_when: false

- name: restart services using outdated libraries (needrestart < 1.0)
  shell: needrestart -bra 2>/dev/null
  register: result
  changed_when: "result.stdout != ''"
  when: needrestart_version_lt_one.rc == 0

- name: restart services using outdated libraries (needrestart >= 1.0)
  shell: needrestart -blra 2>/dev/null
  register: result
  changed_when: "result.stdout != ''"
  when: needrestart_version_lt_one.rc == 1

- name: check for pending kernel updates
  command: needrestart -bk
  register: needrestart_result
  changed_when: False
  when: needrestart_version_lt_one.rc == 1

- name: email root if machine needs a reboot
  # non-recent versions of needrestart read from stdin if newer kernels
  # are available, since we use '-b'
  shell: needrestart -bk | mail -s "$(hostname -f) needs a reboot" root
  # see https://github.com/ansible/ansible/issues/2769:
  when: "'NEEDRESTART-KSTA: 0' not in '{{ needrestart_result.stdout }}' and
         'NEEDRESTART-KSTA: 1' not in '{{ needrestart_result.stdout }}'"
