- name: install apticron
  package: name=apticron state=present

- name: install needrestart
  package: name=needrestart state=present

- name: make needrestart default to list services only
  lineinfile: dest=/etc/needrestart/conf.d/list-services-only.conf
              line="$nrconf{restart} = 'l';"
              state=present create=yes mode=0644

- name: make needrestart default to list required reboots only
  lineinfile: dest=/etc/needrestart/conf.d/list-required-reboots-only.conf
              regexp="\$nrconf\{kernelhints\}"
              line="$nrconf{kernelhints} = -1;"
              state=present create=yes mode=0644

- name: check needrestart version
  register: needrestart_version_lt_one
  shell: needrestart --version | grep "needrestart 0"
  changed_when: false
  failed_when: false

- name: restart services using outdated libraries (needrestart < 1.0)
  shell: needrestart -ra 2>/dev/null
  register: result
  changed_when: "result.stdout != ''"
  when: needrestart_version_lt_one.rc == 0

- name: restart services using outdated libraries (needrestart >= 1.0)
  shell: needrestart -lra 2>/dev/null
  register: result
  changed_when: "result.stdout != ''"
  when: needrestart_version_lt_one.rc == 1

- name: check for pending kernel updates
  command: needrestart -bk
  register: needrestart_result
  changed_when: False
  when: needrestart_version_lt_one.rc == 1

- name: email root if machine needs a reboot
  # non-recent versions of needrestart read from stdin if newer kernels
  # are available, since we use '-b'
  shell: needrestart -bk | mail -s "$(hostname -f) needs a reboot" root
  # see https://github.com/ansible/ansible/issues/2769:
  when: "'NEEDRESTART-KSTA: 3' in '{{ needrestart_result.stdout }}'"
  when: needrestart_version_lt_one.rc == 1
