
- name: create cron scripts for disk space alert
  lineinfile:   dest=/etc/cron.hourly/90-disk_space_alert
                line='#!/bin/sh'
                insertbefore=BOF
                create=yes
                mode=700
  when: disk_space_alert_percentage >= 0

- name: delete cron scripts for disk space alert
  file: path=/etc/cron.hourly/90-disk_space_alert
        state=absent
  when: disk_space_alert_percentage < 0

- name: set up weekly clearing of apt cache
  lineinfile: dest=/etc/cron.hourly/90-disk_space_alert
          line='/opt/admintools/disk_space_alert_all.sh
                  {{ disk_space_alert_percentage }}'
          regexp=".*disk_space_alert_all.*"
          create=yes
  when: disk_space_alert_percentage >= 0
