- name: install nano
  apt: package=nano

- name: set nano as default editor in environment variable
  lineinfile:
    dest: "{{ item }}"
    regexp: 'export EDITOR='
    line: 'export EDITOR=nano'
    create: yes
  with_items:
    - /etc/profile.d/default-editor
    - /etc/zsh/zshenv
