- name: uninstall system packages for rootkit detection
        (malicious software will probably detect those anyway)
  package: name={{ item }} state=absent
  with_items:
    - rkhunter
    - unhide
    - chkrootkit


- name: checkout Lynis
  git: repo=https://github.com/CISOfy/lynis.git
       dest=/tmp/lynis
       force=yes



# we cannot use ini_file, since Lynis does not use standard INI files
- name: create sections in Lynis configuration
  lineinfile: dest=/tmp/lynis/custom.prf
              line="[{{ item.section }}]"
              create=yes
  with_items: "{{ lynis_global_options |
                  union( lynis_extra_options | default([]) ) }}"

# we cannot use ini_file, since Lynis does not use standard INI files
- name: put configuration key-value pairs in Lynis configuration
  lineinfile: dest=/tmp/lynis/custom.prf
              line="{{ item.option }}"
              insertafter="\[{{ item.section }}\]"
  with_items: "{{ lynis_global_options |
                  union( lynis_extra_options | default([]) ) }}"



- name: check if swap partition is configured or active
  shell: grep -q swap /etc/fstab || mount | grep -q swap
  register: swap_check
  changed_when: false
  ignore_errors: yes

- name: disable check for swap partition if none was found
  lineinfile: dest=/tmp/lynis/custom.prf
              line="skip-test=FILE-6336"
              insertafter="\[security\]"
  when: swap_check.rc != 0



- name: disable kernel-related check when OS-level virtualized
  lineinfile: dest=/tmp/lynis/custom.prf
              line="skip-test={{ item }}"
              insertafter="\[security\]"
  when: ansible_virtualization_type in ["lxc"]
  with_items:
    # check for kernel updates:
    - KRNL-5788
    # check for sysctl values:
    - KRNL-6000
    # check for NTP client (clock should be controlled by hypervisor):
    - TIME-3104


- name: run Lynis
  shell: 'cd /tmp/lynis &&
          ./lynis audit system --cronjob | \
            cat -v | \
              sed -r "s/\^\[\[[0-9;]+m//g" | \
                mail -s "$(hostname) hardening report" root'

- name: remove lynis
  file: path=/tmp/lynis state=absent
