- name: set hostname and fqdn in /etc/hosts
  lineinfile: dest=/etc/hosts
              regexp="{{ item.regexp }}"
              line="{{ item.line }}"
  with_items:
      - {
        regexp: '^127\.0\.0\.1\s+',
        line: "127.0.0.1 {{ ansible_fqdn }} {{ ansible_hostname }} localhost"
        }
      - {
        regexp: "^::1",
        line: "::1 {{ ansible_fqdn }} {{ ansible_hostname }} localhost ip6-localhost ip6-loopback"
        }

- name: ensure lookup in /etc/hosts before dns
  lineinfile: line="order hosts,bind"
              regexp="^\s*order\s.*"
              dest="/etc/host.conf"
              insertbefore="^\s*multi\s.*"
