# includes that to not alter the system can be made conditional here
# (otherwise, we might have to undo stuff when variables change)

# keep installing admintools the first thinng to do

- import_tasks: git-install.yml

- import_tasks: admintools.yml

# keep configuring packages to install other packages the second thing to do
- import_tasks: apt-config.yml

# before installing new packages, upgrade:
- import_tasks: apt-upgrade.yml

- import_tasks: git-config.yml

- import_tasks: apt-tools.yml

- import_tasks: editor.yml

- import_tasks: shell.yml

- import_tasks: interactive-monitors.yml

- import_tasks: system-information.yml

- import_tasks: net-utils.yml

- import_tasks: postfix.yml

- import_tasks: umask.yml

- import_tasks: ntp.yml

- import_tasks: haveged.yml

- import_tasks: ssh_hardening.yml
  tags: [ssh_hardening]

- import_tasks: scheduling_and_detaching.yml

- import_tasks: logging-and-accounting.yml

- import_tasks: hostname_and_lookups.yml

- import_tasks: certbot.yml

- import_tasks: accounts-hardening.yml

- import_tasks: file-system-maintenance.yml

- import_tasks: email-send-test.yml
  when: do_email_send_test
  tags: [email_test]

- import_tasks: apache2.yml
- import_tasks: nginx.yml

- import_tasks: service_priorities.yml

- import_tasks: dbms.yml

- name: check if this the remote machine runs Armbian
  stat: path=/etc/armbian.txt
  register: stat_armbian_txt_stat_result
- import_tasks: armbian.yml
  when: stat_armbian_txt_stat_result.stat.exists

- include_tasks: apparmor.yml

# this should be the last line:
- import_tasks: hardening-report.yml
  when: create_reports
  tags: [report, hardening-report]
