# includes that to not alter the system can be made conditional here
# (otherwise, we might have to undo stuff when variables change)

# keep installing admintools the first thinng to do

- include_tasks: git-install.yml

- include_tasks: admintools.yml

# keep configuring packages to install other packages the second thing to do
- include_tasks: apt-config.yml

# before installing new packages, upgrade:
- include_tasks: apt-upgrade.yml

- include_tasks: git-config.yml

- include_tasks: apt-tools.yml

- include_tasks: editor.yml

- include_tasks: shell.yml

- include_tasks: interactive-monitors.yml

- include_tasks: system-information.yml

- include_tasks: net-utils.yml

- include_tasks: postfix.yml

- include_tasks: umask.yml

- include_tasks: ntp.yml

- include_tasks: haveged.yml

- include_tasks: ssh_hardening.yml

- include_tasks: scheduling_and_detaching.yml

- include_tasks: logging-and-accounting.yml

- include_tasks: hostname_and_lookups.yml

- include_tasks: certbot.yml

- include_tasks: accounts-hardening.yml

- include_tasks: disk_space_alert.yml

- include_tasks: email_send_test.yml
  when: do_email_send_test
  tags: [email_test]

- include_tasks: apache2.yml
- include_tasks: nginx.yml

# this should be the last line:
- include_tasks: hardening-report.yml
  when: create_reports
  tags: [report, hardening-report]
