# includes that to not alter the system can be made conditional here
# (otherwise, we might have to undo stuff when variables change)

# keep installing admintools the first thinng to do

- include: git-install.yml

- include: admintools.yml

# keep configuring packages to install other packages the second thing to do
- include: apt-config.yml

# before installing new packages, upgrade:
- include: apt-upgrade.yml

- include: git-config.yml

- include: apt-tools.yml

- include: editor.yml

- include: shell.yml

- include: interactive-monitors.yml

- include: system-information.yml

- include: net-utils.yml

- include: postfix.yml

- include: umask.yml

- include: ntp.yml

- include: haveged.yml

- include: ssh_hardening.yml
  tags: [ssh_hardening]

- include: scheduling_and_detaching.yml

- include: logging-and-accounting.yml

- include: hostname_and_lookups.yml

- include: certbot.yml

- include: accounts-hardening.yml

- include: disk_space_alert.yml

- include: email_send_test.yml
  when: do_email_send_test
  tags: [email_test]

- include: apache2.yml
- include: nginx.yml

- include: service_priorities.yml

- name: check if this the remote machine runs Armbian
  stat: path=/etc/armbian.txt
  register: stat_armbian_txt_stat_result
- include: armbian.yml
  when: stat_armbian_txt_stat_result.stat.exists

# this should be the last line:
- include: hardening-report.yml
  when: create_reports
  tags: [report, hardening-report]
