# keep installing admintools the first thinng to do
- include: git-install.yml
- include: admintools.yml

# keep configuring packages to install other packages the second thing to do
- include: apt-config.yml

# before installing new packages, upgrade:
- include: apt-upgrade.yml

- include: git-config.yml
- include: apt-tools.yml
- include: editor.yml
- include: shell.yml
- include: interactive-monitors.yml
- include: system-information.yml
- include: net-utils.yml
- include: postfix.yml
- include: rootkit-detection.yml
  tags: [report]
- include: umask.yml
- include: ntp.yml
- include: haveged.yml
- include: ssh_hardening.yml
- include: apt-dater.yml
- include: scheduling_and_detaching.yml
- include: logging.yml
- include: hostname_and_lookups.yml
- include: certbot.yml
- include: accounts-hardening.yml
- include: disk_space_alert.yml
- include: email_send_test.yml
  tags: [email_test]
- include: apache2.yml

# this should be the last line:
- include: hardening-report.yml
  tags: [report, hardening-report]
