- name: check if nginx is installed
  register: nginx_installed_check
  shell: type nginx
  changed_when: no
  failed_when: no

- name: create Diffie-Hellman parameters (takes some minutes)
  command: openssl dhparam -out /etc/nginx/ssl/dhparam.pem 2048
  args:
    creates: /etc/nginx/ssl/dhparam.pem
  when: nginx_installed_check.rc == 0

- name: add nginx configuration files
  blockinfile:
    path: "/etc/nginx/{{ item | dirname | basename }}/{{ item | basename }}"
    state: present
    block: "{{ lookup('file', item) }}"
    force: yes
    create: yes
  with_fileglob:
    - nginx/conf.d/*.conf
    - nginx/snippets/*.conf
  when: nginx_installed_check.rc == 0
  notify: restart nginx
