- name: check if nginx is installed
  register: nginx_installed_check
  shell: type nginx
  changed_when: no
  failed_when: no

- name: create required directories
  file: path="{{ item }}" state=directory
  with_items:
    - /etc/nginx/ssl
    - /etc/nginx/snippets
  when: nginx_installed_check.rc == 0

- name: create Diffie-Hellman parameters (takes some minutes)
  command: openssl dhparam -out /etc/nginx/ssl/dhparam.pem 2048
  args:
    creates: /etc/nginx/ssl/dhparam.pem
  when: nginx_installed_check.rc == 0

- name: add configuration files for nginx
  blockinfile:
    path: "/etc/{{ item }}"
    state: present
    block: "{{ lookup('file', item) }}"
    force: yes
    create: yes
  with_items:
    - nginx/conf.d/50-generic-hardening.conf
    - nginx/snippets/ssl.conf
  when: nginx_installed_check.rc == 0
  notify: restart nginx
