- name: uninstall ntp in LXC
  package: name=ntp state=present
  when: ansible_virtualization_type == "lxc"

- name: install ntp
  package: name=ntp state=present
  when: ansible_virtualization_type != "lxc"

- stat: path=/etc/etc/ntp.conf
  register: conf_stat

- name: backup and remove ntp configuration
  command: "mv /etc/etc/ntp.conf
               /etc/etc/ntp.conf.BAK_ansible_{{ ansible_date_time.iso8601 }}"
  when: conf_stat.stat.islnk is defined and conf_stat.stat.islnk == False

- name: ntp configuration (symlink to admintools)
  file: src=/opt/admintools/etc/ntp.conf
        dest=/etc/etc/ntp.conf
        state=link
