- name: write systemd override file
  blockinfile:
    dest: "/etc/systemd/system/{{ item.key }}.service.d/nice.conf"
    create: yes
    mode: 644
    block: |
      [Service]
      Nice={{ item.value }}
  with_dict: "{{ service_priorities |
                 combine(extra_service_priorities | default({})) }}"
  notify: reload systemd daemon
