- name: configure PAM to enforce umask at login time
  register: set_umask_pam
  lineinfile:
    dest: /etc/pam.d/common-session
    regexp: 'session\s+optional\s+pam_umask.so'
    line: 'session    optional     pam_umask.so umask=077'
    create: no

- name: set default umask to 077 in /etc/login.defs
  register: set_umask_logindefs
  lineinfile:
    dest: /etc/login.defs
    regexp: '^UMASK\s+[0-9]+'
    line: 'UMASK           077'
    create: yes

- name: set umask to 077 in /etc/init.d/rc
  register: set_umask_logindefs
  lineinfile:
    dest: /etc/init.d/rc
    regexp: '^\s*umask\s.*'
    line: 'umask 077'
    create: yes

- name: tell debsums to ignore changes in /etc/init.d/rc
  register: set_umask_logindefs
  lineinfile:
    dest: /etc/debsums-ignore
    line: "^/etc/init.d/rc$"
    create: yes

- name: check umask for root to be at least 026
  register: root_umask_result
  shell:  "sh -c '[ $(umask) -ge 26 ]'"
  changed_when: false
  failed_when: root_umask_result.rc != 0
  when: not set_umask_pam.changed
