- name: install editor and file viewer
  package:
    name:
      - less
      - nano


- name: set nano as default editor in environment variable
  lineinfile:
    dest: "{{ item }}"
    regexp: 'export EDITOR='
    line: 'export EDITOR=nano'
    create: yes
  with_items:
    - /etc/profile.d/default-editor
    - /etc/zsh/zshenv


- name: get list of existing systemd timers
  register: systemctl_list_units_result
  shell: systemctl list-timers --all --no-legend
  changed_when: false

- name: disable regular regeneration of man pages
  service:
    name: man-db.timer
    state: stopped
    enabled: no
  when: '" man-db.timer " in systemctl_list_units_result.stdout'
