configure_rsync_backup: True
rsync_backup_script: /etc/cron.daily/999-rsync-backup
rsync_backup_remote_host: example.com
rsync_backup_remote_port: 22
rsync_backup_remote_user: "{{ ansible_hostname }}"
rsync_backup_dir_pairs:
  - { local_dir: "/", remote_dir: "/backup"}

arpwatch_enabled: yes
use_process_accounting: yes

needs_usb_storage: no
needs_firewire_storage: no

# multiples of .1s for the 1-128 range, and in 30s for the 129-255 range
western_digital_idle_timer: 148
