configure_rsync_backup: True
rsync_backup_script: /etc/cron.daily/999-rsync-backup
rsync_backup_remote_host: example.com
rsync_backup_remote_port: 22
rsync_backup_remote_user: "{{ ansible_hostname }}"
rsync_backup_dir_pairs:
  - { local_dir: "/", remote_dir: "/backup"}

use_arpwatch: yes
