- name: 'remove legacy: apt-dater client'
  apt: package=apt-dater-host state=absent

- name: 'remove legacy: apt-dater user'
  user: name=apt-dater state=absent remove=yes

- name: "remove legacy: revoke apt-dater user's sudo rights"
  lineinfile: dest=/etc/sudoers.d/apt-dater-host
              regexp='^apt-dater ALL=NOPASSWD:.*'
              create=yes mode=0440 state=absent

- name: 'remove legacy: make sure there are no sudo grants for the apt-dater user'
  shell: "[ `sudo -lU apt-dater | grep -c NOPASSWD` -eq 0 ]"
  changed_when: false
