- name: get Western Digital drives present
  set_fact:
    western_digital_drives: "{{ western_digital_drives|default([]) + [item.key] }}"
  when: item.value.rotational == "1" and
        item.value.model != None and
        item.value.model | match("WDC .+")
  with_dict: "{{ ansible_devices }}"
  loop_control:
    label: "{{ item.key }}"

- name: "{{ 'install' if western_digital_drives|default(false)
            else 'uninstall' }} idle3 tools for Western Digital drives"
  package:
    name: idle3-tools
    state: "{{ 'present' if western_digital_drives|default(false)
                else 'absent' }}"

- name: set IntelliPark timeout for Western Digital drives
  command: "idle3ctl -s {{ western_digital_idle_timer }} /dev/{{ item }}"
  with_items: "{{ western_digital_drives|default([]) }}"
  changed_when: false
