- name: install microcode packages
  package:
    name: "{{ item.key }}"
    state: "{{ 'present' if item.value else 'absent' }}"
  with_dict:
    amd64-microcode: "{{ 'AuthenticAMD' in ansible_processor }}"
    intel-microcode: "{{ 'GenuineIntel' in ansible_processor }}"



- name: install firmware packages
  package:
    name: firmware-linux
    state: present
  when: not armbian



- name: un/install firmware updater
  package:
    name: fwupd
    state: "{{ 'present' if use_fwupd else 'absent' }}"

- name: override systemd units of fwupd
  blockinfile:
    dest: "/etc/systemd/system/{{ item.key }}.d/ansible.conf"
    create: yes
    mode: 0644
    marker: "# {mark} ANSIBLE MANAGED BLOCK ({{ item.value | basename}})"
    block: "{{ lookup('file', item.value) }}"
    state: "{{ 'present' if use_fwupd else 'absent' }}"
  with_dict:
    fwupd-refresh.timer: fwupd-refresh.timer.d/refresh-less-often.conf
    fwupd-refresh.service: fwupd-refresh.service.d/email-notifications.conf
  notify: reload systemd daemon



- name: check if the machine was booted using UEFI
  register: stat_sys_firmware_efi_result
  stat:
    path: /sys/firmware/efi
  when: support_for_secure_boot

- name: un/install signed Secure Boot chain-loading bootloader
  package:
    name: shim-signed
    state: "{{ 'present' if support_for_secure_boot
                         and stat_sys_firmware_efi_result.stat.exists
                else 'absent' }}"



- name: install ``irqbalance`` on multi-core machines
  package:
    name: irqbalance
    state: "{{ 'present' if ansible_processor_vcpus > 1 else 'absent' }}"

- name: enable and start ``irqbalance`` on multi-core machines
  service:
    name: irqbalance
    state: started
    enabled: yes
  when: ansible_processor_vcpus > 1



- name: get Western Digital drives present
  set_fact:
    western_digital_drives: "{{ western_digital_drives|default([]) + [item.key] }}"
  when: item.value.rotational == "1" and
        item.value.model != None and
        item.value.model is match("WDC .+")
  with_dict: "{{ ansible_devices }}"
  loop_control:
    label: "{{ item.key }}"

- name: "{{ 'install' if western_digital_drives|default(false)
            else 'uninstall' }} idle3 tools for Western Digital drives"
  package:
    name: idle3-tools
    state: "{{ 'present' if western_digital_drives|default(false)
                else 'absent' }}"

- name: disable IntelliPark for Western Digital drives
        (power management takes care)
  # check if ``idle3ctl`` works on this drive;
  #   if so, disable IntelliPark;
  #   if not, exit with return code ``0``
  shell: "idle3ctl -g /dev/{{ item }}
          && idle3ctl -d /dev/{{ item }}
          || true"
  with_items: "{{ western_digital_drives|default([]) }}"
  changed_when: false
