- name: install microcode packages
  package:
    name: "{{ item.key }}"
    state: "{{ 'present' if item.value else 'absent' }}"
  with_dict:
    amd64-microcode: "{{ 'AuthenticAMD' in ansible_processor }}"
    intel-microcode: "{{ 'GenuineIntel' in ansible_processor }}"



- name: install firmware packages
  package:
    name: firmware-linux
    state: present
  when: not armbian



- name: install ``irqbalance`` on multi-core machines
  package:
    name: irqbalance
    state: "{{ 'present' if ansible_processor_vcpus > 1 else 'absent' }}"

- name: enable and start ``irqbalance`` on multi-core machines
  service:
    name: irqbalance
    state: started
    enabled: yes
  when: ansible_processor_vcpus > 1



- name: get Western Digital drives present
  set_fact:
    western_digital_drives: "{{ western_digital_drives|default([]) + [item.key] }}"
  when: item.value.rotational == "1" and
        item.value.model != None and
        item.value.model is match("WDC .+")
  with_dict: "{{ ansible_devices }}"
  loop_control:
    label: "{{ item.key }}"

- name: "{{ 'install' if western_digital_drives|default(false)
            else 'uninstall' }} idle3 tools for Western Digital drives"
  package:
    name: idle3-tools
    state: "{{ 'present' if western_digital_drives|default(false)
                else 'absent' }}"

- name: disable IntelliPark for Western Digital drives
        (power management takes care)
  # check if ``idle3ctl`` works on this drive;
  #   if so, disable IntelliPark;
  #   if not, exit with return code ``0``
  shell: "idle3ctl -g /dev/{{ item }}
          && idle3ctl -d /dev/{{ item }}
          || true"
  with_items: "{{ western_digital_drives|default([]) }}"
  changed_when: false
