# we use /etc/cron.daily instead of crontab since it is compatible
# with anacron

- name: install rsync for doing backups
  package:
    name: rsync
  when: configure_rsync_backup

# this is separate from the "blockinfile" below because the shebang
# must be the very first line of the script
- name: create script file for daily backups
  lineinfile:   dest="{{ rsync_backup_script }}" regexp="^#!.*"
                state=present create=yes mode=u+x insertbefore=BOF
                line='#!/bin/bash'
  when: configure_rsync_backup

- name: add command to script for daily backups
  blockinfile:
    dest: "{{ rsync_backup_script }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR {{ item.local_dir }}"
    block: |
      timeout 23h \
        /opt/admintools/scripts/wait-for \
          -P "{{ rsync_backup_remote_host }}:{{ rsync_backup_remote_port }}" \
          --ac \
            /opt/admintools/scripts/backup-to-sftp \
              -p {{ rsync_backup_remote_port }} \
              -s "{{ item.local_dir }}" \
                "{{ rsync_backup_remote_host }}" \
                "{{ item.remote_dir }}"
  with_items: "{{ rsync_backup_dir_pairs }}"
  when: configure_rsync_backup

- name: delete rsync backup script if backup is disabled
  file: path="{{ rsync_backup_script }}" state=absent
  when: not configure_rsync_backup
