- name: check if remote machine runs Armbian
  stat:
    path: /etc/armbian.txt
  register: stat_armbian_txt_stat_result

- name: set fact if remote machine runs Armbian
  set_fact:
    armbian: stat_armbian_txt_stat_result.stat.exists
