- name: add configuration files for sysctl (kernel parameters)
  file: src="/opt/admintools/etc/sysctl.d/{{ item }}"
        dest="/etc/sysctl.d/{{ item }}"
        state=link
  with_items:
    - 90-hardening.conf
    - 80-net-tuning.conf
    - 50-reboot-on-panic.conf
