- name: install software watchdog
  package:
    name: watchdog
    state: present

- name: configure watchdog
  lineinfile:
    dest: /etc/watchdog.conf
    regexp: '^#?\s*{{ item.key|regex_escape }}'
    line: '{{ item.key }} = {{ item.value }}'
    state: present
  with_dict:

    # how often watchdogs checks (seconds):
    "interval": 57
    # allow no writes to watchdog device before rebooting (seconds):
    "watchdog-timeout": 120

    # allow errors to persist before rebooting (seconds)
    "retry-timeout": 300

    "max-load-15": "{{ (ansible_processor_vcpus + ansible_devices|count) * 4 }}"
    "max-load-5": "{{ (ansible_processor_vcpus + ansible_devices|count) * 8 }}"
    "max-load-1": "{{ (ansible_processor_vcpus + ansible_devices|count) * 16 }}"

- name: enable watchdog service
  service:
    name: watchdog
    state: started
    enabled: yes
