- name: get temporary file
  register: iptables_workaround_tempfile
  tempfile:
    state: file

- name: remove duplicate rules
  shell: "awk '/^COMMIT$/ { delete x; }; !x[$0]++' {{ rules_file }}
          > {{ iptables_workaround_tempfile.path }};
          mv {{ iptables_workaround_tempfile.path }} {{ rules_file }}"

- name: reload iptables
  service:
    name: netfilter-persistent
    state: restarted
