- name: backup currently persisted iptables
  copy:
    remote_src: true
    src: "{{ rules_file }}"
    dest: "{{ rules_backup_file }}"

- name: persist iptables
  command: "{{ dump_command|quote }} -f {{ rules_file|quote }}"

- name: schedule deletion of iptables backup file a year from now
  at:
    command: "rm -f {{ rules_backup_file|quote }}"
    count: 365
    units: days

  # ``at`` might not be installed and that's okay
  ignore_errors: true
