# In some cases, the helper furl file needs to be regenerated.
# Lets delete it in order to be sure to read the re-written file later on.
#
# Using a separate handler, say "regenerate helper furl file",
# is tricky since if "restart helper" is notified fist, the node
# first restarts and /then/ the helper furl file is deleted – what
# is problematic.
# Deleting the file prior every restart was considered less pain than
# trying to hack around Ansibles order of execution regarding handlers.
#
# The noop command silences "Consider using file module…"
- name: restart helper
  shell: ":;
          rm -f '{{ tahoe_basedir }}/node/private/helper.furl';
          {{ tahoe_bin }} -q restart '{{ tahoe_basedir }}/node'"
