# in your variables you *need to* set
#gitlab_runner_api_url: …
#gitlab_runner_api_token: …
#gitlab_runner_registration_token: …
#gitlab_runner_description: …

# in variables, you can override these defaults:
gitlab_runner_tag_list: []
gitlab_runner_run_untagged: yes
gitlab_runner_locked: no
gitlab_runner_access_level: not_protected

gitlab_runner_concurrent: 1

# Divide available memory by the concurrency level but reserve 1G.
gitlab_runner_docker_memory_limit: "{{
  (ansible_memtotal_mb - 1024) / gitlab_runner_concurrent | int
}}m"

# CPU overload is not too bad, so we grant every container to use 95 %
# of the available cores
gitlab_runner_docker_cpus: "{{
  [ansible_processor_vcpus * 0.95, 1] | max | int
}}"

# If you want the jobs to be more nice, you could reserve one core for
# non-job loads, and  divide the rest of the  available cores by the
# number of concurrent jobs (but assign at least one core):
#gitlab_runner_docker_cpus: "{{
#  [
#    (ansible_processor_vcpus - 1) / gitlab_runner_concurrent,
#    1
#  ] | max | int
#}}"
