# you can use ``fail2ban_jails_extra_config`` to override values
fail2ban_jails_config:
  DEFAULT:
    bantime: 1200
    # window for ``maxretry``
    findtime: 600
    # retries before banning a host:
    maxretry: 3

    destemail: root
    sender: root

  sshd-ddos:
    enabled: true
