fail2ban_jails_config_file: /etc/fail2ban/jail.d/via-ansible.conf

# Statically sets Fail2ban jail configuration.
# You can use ``fail2ban_jails_extra_config`` to override values.
fail2ban_jails_config:
  DEFAULT:
    bantime: 1200
    # window for ``maxretry``
    findtime: 600
    # retries before banning a host:
    maxretry: 3

    destemail: root
    sender: root

  sshd-ddos:
    enabled: true

# Maps from shell commands to jails to enable. If command exits with
# code 0, the listed jails will be enabled, disabled otherwise.
# You can use ``fail2ban_jails_extra_auto_enable`` to override values.
fail2ban_jails_auto_enable:
  'apache2 -v':
    - apache-auth
    - apache-badbots
    - apache-botsearch
    - apache-modsecurity
    - apache-modsecurity
    - apache-nohome
    - apache-noscript
    - apache-overflows
    - apache-shellshock
  'dovecot --version':
    - 'dovecot'
  'nginx -v':
    - nginx-botsearch
    - nginx-http-auth
  'mysqld --version':
    - mysqld-auth
  'postconf -nh | grep -q rbl':
    - postfix-rbl
  'postconf -nh | grep -q sasl':
    - postfix-sasl
