- name: check return code of '{{ fail2ban_jail_auto_enable.key }}'
  register: check_command_result
  shell: "{{ fail2ban_jail_auto_enable.key }}"
  changed_when: false
  failed_when: false

- name: "{{ 'enable' if check_command_result.rc == 0 else 'disable'}}
         jails corresponding to '{{ fail2ban_jail_auto_enable.key }}'"
  ini_file:
    path: "{{ fail2ban_jails_config_file }}"
    section: "{{  item }}"
    option: enabled
    value: true
    state: "{{ 'present' if check_command_result.rc == 0 else 'absent'}}"
  with_items: '{{ fail2ban_jail_auto_enable.value }}'
