- name: "{{ outer_item.ip_version}} :
         custom chain '{{ chain_name }}' : check if exists already"
  register: iptables_list_result
  command: "{{ outer_item.command }} -t {{ table }} -L"
  changed_when: false

- name: "{{ outer_item.ip_version}} :
         custom chain '{{ chain_name }}' : delete"
  command: "{{ outer_item.command }} -t {{ table }} --delete-chain {{ chain_name }}"
  when: not add_to_chain
  notify: "persist {{ outer_item.ip_version }} tables"

- name: "{{ outer_item.ip_version}} :
         custom chain '{{ chain_name }}' : create"
  command: "{{ outer_item.command }} -t {{ table }} --new-chain {{ chain_name }}"
  when: add_to_chain and
        'Chain ' + chain_name not in iptables_list_result.stdout
  notify: "persist {{ outer_item.ip_version }} tables"

- name: "{{ outer_item.ip_version}} :
         custom chain '{{ chain_name }}' : add to '{{ add_to_chain }}'"
  iptables:
    ip_version: "{{ outer_item.ip_version }}"
    table: "{{ table }}"
    chain: "{{ add_to_chain }}"
    jump: "{{ chain_name }}"
    state: "{{ 'present' if add_to_chain else 'absent' }}"
  notify: "persist {{ outer_item.ip_version }} tables"
