- name: uninstall deprecated distribution of Tahoe LAFS
  pip: name=allmydata-tahoe  state=absent
       executable={{ pip_command|default("pip") }}

- include: pip.yml
  when: not tahoe_repository

- include: git.yml
  when: tahoe_repository

- name: add Tahoe binaries to PATH
  lineinfile: dest="{{ item.dest }}"
              line="{{ item.line }}"
              state=present
              create=yes
  when: "'{{ item.shell }}' in '{{ ansible_user_shell }}'"
  with_items:
    - shell: bash
      dest: ~/.bash_profile
      line: PATH="~/.local/bin:$PATH"
    - shell: zsh
      dest: ~/.zprofile
      line: path=(~/.local/bin ~/bin/ $path)

- name: create Tahoe base directory
  file: path={{ tahoe_basedir }}
        state=directory
