- name: _restart sshd
  service: name=ssh state=restarted

# This does not actually restart SSHd but tests its configuration and
# notifies the actual restart handler.
# Once https://github.com/ansible/ansible/issues/14270 is resolved,
# this can be done properly using a block.
- name: restart sshd
  command: sshd -T
  notify: _restart sshd

- name: restart postfix
  service: name=postfix state=restarted

- name: restart opendkim
  service: name=opendkim state=restarted
  when: postfix_dkim_keys

- name: reload systemd daemon
  command: systemctl daemon-reload
  when: ansible_service_mgr == "systemd"

- name: rehash aliases
  command: postalias /etc/aliases

- name: restart apache2
  shell: apache2ctl configtest && apache2ctl restart

- name: restart nginx
  service: name=nginx state=restarted
