- name: restart sshd
  service: name=ssh state=restarted

- name: restart postfix
  service: name=postfix state=restarted

- name: restart opendkim
  service: name=opendkim state=restarted
  when: postfix_dkim_keys

- name: reload systemd daemon
  command: systemctl daemon-reload
  when: ansible_service_mgr == "systemd"

- name: rehash aliases
  command: postalias /etc/aliases

- name: restart apache2
  shell: apache2ctl configtest && apache2ctl restart

- name: restart nginx
  service: name=nginx state=restarted
