- name: install mysql-server
  apt: package=mysql-server

- name: set mysqldump to ignore mysql's events
  ini_file: dest="/etc/mysql/conf.d/mysqldump_events.cnf"
            section=mysqldump
            option=ignore-table
            value=mysql.event
            mode=644
  notify: restart mysqld

- name: set mysqldump to also dump events
  lineinfile:   dest="/etc/mysql/conf.d/mysqldump_events.cnf"
                insertafter="[mysqldump]"
                line="events"
                regexp="^events(\s+=?\s*)?"
                mode=644
  notify: restart mysqld

- name: install automysqlbackup
  apt: package=automysqlbackup

- include: default-character-set.yml
