- name: "{{ container_name }} : destroy container"
  command: >
    lxc-destroy
      --name '{{ container_name }}'
      --snapshots
      --force
  become: yes
  become_user: "{{ lxc_user }}"

- name: "{{ container_name }} : remove network bridge configuration file"
  file:
    path: "/etc/network/interfaces.d/lxc-br-{{ container_name }}"
    state: absent
  notify: restart networking
