# This fails, I guess, when the user still runs a container. But that's
# okay. Let's require the container to be stopped before removal.
- name: "{{ container_name }} : remove user (and it's home)"
  user:
    name: "{{ container_user }}"
    state: absent
    remove: yes



- name: "{{ container_name }} : remove network bridge configuration file"
  file:
    path: "/etc/network/interfaces.d/lxc-br-{{ container_name }}"
    state: absent
  notify: restart networking



- name: "{{ container_name }} : unconfigure access bridge
         '{{ container_bridge }}'"
  lineinfile:
    path: /etc/lxc/lxc-usernet
    state: absent
    regexp: '^{{
        container_name | regex_escape()
      }}\s+.*\s+{{
        container_bridge | regex_escape()
      }}.*'
