- name: set helper furl
  ini_file: dest="{{ tahoe_basedir }}/node/tahoe.cfg"
            section=client
            option=helper.furl
            value='{{ tahoe_helper_furl }}'
  notify: restart node
