- name: create tahoe user
  user: name={{tahoe_user}}

- name: install required packages
  package: name="{{ item }}"
  with_items:
    - python-pip
    - build-essential
    - libssl-dev
    - libffi-dev
    - python-dev
