- name: create tahoe user
  user: name={{tahoe_user}}
        shell="{{ ansible_user_shell }}"

- name: install required packages
  apt: name="{{ item }}" install_recommends=yes
  with_items:
    - python-pip
    - python-pkg-resources
    - build-essential
    - libssl-dev
    - libffi-dev
    - python-dev

- name: check pip version
  register: pip_version
  command: pip --version
  changed_when: false

- name: upgrade away from pip 8.1.1
  pip: name=pip state=latest
  when: "' 8.1.1 ' in pip_version.stdout"
