- name: install real-time kernel
  package:
    name: "linux-image-rt-{{ ansible_kernel.split('-')[-1] }}"
    state: present

#~ - name: remove non-real-time kernel
  #~ package:
    #~ name: "linux-image-{{ ansible_kernel.split('-')[-1] }}"
    #~ state: absent

- name: add udev rules to disable frequency scaling etc.
  blockinfile:
    path: "/etc/udev/rules.d/{{ item.path }}"
    block: "{{ lookup('file', item.src) }}"
    create: yes
  with_filetree: etc/udev/rules.d
