- name: create shell scripts to delay cron tasks
  lineinfile:
    dest: /etc/cron.{{ item }}/000-delay
    line: '#!/bin/sh'
    insertbefore: BOF
    create: yes
    mode: 500

  with_items:
     - hourly
     - daily
     - weekly
     - monthly

- name: add delay to cron tasks
  lineinfile:
    dest: /etc/cron.{{ item.key }}/000-delay
    regexp: '^sleep '
    line: >
      sleep $(
        python -c 'import random as r; print(
          r.randint({{ item.min }}, {{ item.max }})
        )'
      )m

  with_dict:
    hourly:
      min: 15
      max: 45
    monthly:
      min: 100
      max: 200
    weekly:
      min: 200
      max: 300
    daily:
      min: 300
      max: 400
