- name: create shell scripts to delay cron tasks
  lineinfile:
    dest: /etc/cron.{{ item }}/000-delay
    line: '#!/bin/sh'
    insertbefore: BOF
    create: yes
    mode: 500

  with_items:
     - hourly
     - daily
     - weekly
     - monthly

- name: add delay to cron tasks
  lineinfile:
    dest: /etc/cron.{{ item.key }}/000-delay
    line: sleep $({{ random_integer_cmd }}){{ item.value }}
    regexp: '^sleep '

  with_dict:
    hourly: m
    daily: h
    weekly: h
    monthly: h
