- name: sysctl reload
  command: sysctl --system

- name: update grub
  command: update-grub
  notify: notify root about pending reboot due to updated grub

- name: notify root about pending reboot due to updated grub
  mail:
    subject: "{{ ansible_fqdn }} needs a reboot (Grub updated) EOM"
    body: " "
  notify: grub updated

- name: reload systemd daemon
  command: systemctl daemon-reload
  when: ansible_service_mgr == "systemd"

# fails every 2nd time, probably Debain Bug #772826
- name: restart watchdog
  register: restart_watchdog_result
  service:
    name: watchdog
    state: restarted
  when: use_watchdog
  until: restart_watchdog_result is not failed
  retries: 3
  delay: 1
