- name: sysctl reload
  command: sysctl --system

- name: update grub
  command: update-grub
  notify: notify root about pending reboot due to updated grub

- name: notify root about pending reboot due to updated grub
  mail:
    subject: "{{ ansible_fqdn }} needs a reboot (Grub updated) EOM"
    body: " "
  notify: grub updated

- name: reload systemd daemon
  command: systemctl daemon-reload
  when: ansible_service_mgr == "systemd"

- name: restart watchdog
  service:
    name: watchdog
    state: restarted
  when: use_watchdog
