# not using service module because of
# https://github.com/ansible/ansible-modules-core/issues/5755
- name: add systemd service for mounting swaps marked "noauto"
  register: systemctl_result
  command: systemctl enable /opt/admintools/etc/systemd/system/noauto-swap-partitions.service
  changed_when: systemctl_result.stdout != ""

- name: create directory for systemd-logind drop-ins
  file: dest=/etc/systemd/system/systemd-logind.service.d/
        state=directory

- name: add configuration for systemd-logind to allow hibernation w/o swap
        (swap will be activated right before hibernation)
  file: src=/opt/admintools/etc/systemd/system/systemd-logind.service.d/50-can-hibernate.conf
        dest=/etc/systemd/system/systemd-logind.service.d/50-can-hibernate.conf
        state=link force=yes
